name: Bug report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug]
assignees: 
- nvdaes
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: what-happened
  attributes:
    label: Summary
    description: A clear and concise description of what the bug is.
    placeholder: Sumary of the bug.
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: To reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Step 1.
      2. Step 2...
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
    placeholder: The spected behavior is...
  validations:
    required: true
- type: textarea
  id: log
  attributes:
    label: Relevant log output
    description: If applicable, copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: Version
    description: Product version
    placeholder: "1.0"
  validations:
    required: true
- type: textarea
  id: system
  attributes:
    label: System configuration
    description: Other relevant software or settings.
    placeholder: Program x with y settings
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
    placeholder: Other relevant info.
  validations:
    required: false
