name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [enhancement]
assignees:
- nvdaes
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to provide your suggestion!
- type: input
  id: problem
  attributes:
    label: Problem
    description: A clear and concise description of what the problem is.
    placeholder: I'm always frustrated when...
  validations:
    required: true
- type: textarea
  id: suggestion
  attributes:
    label: Suggestion
    description: A clear and concise description of what you want to happen.
    placeholder: Add ability to...
  validations:
    required: true
- type: textarea
  id: alternatives
  attributes:
    label: Alternatives
    description: A clear and concise description of any alternative solutions or features you've considered.
    placeholder: Alternatively...
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Additional context
    description: Add any other context about the feature request here.
    placeholder: Other relevant info.
  validations:
    required: false
