name: addon

on:
  issues:

jobs:
  addon:
    name: Addon
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Get issue
      uses: actions/github-script@v4
      with:
        script: |
          const issue = github.issues.get({
            repo: context.repo.repo,
            owner: context.repo.owner,
            issue_number: context.issue.number
          })
          console.log(issue)
