name: addon

on:
  issues:
    types: 
      - opened
      - closed
      - reopened

jobs:
  addon:
    name: Addon
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Get issue
      uses: actions/github-script@v4
      with:
        script: |
          const body = context.payload.issue.body
          console.log(body)
