name: Check submitted add-on

on:
  issues:
    types: 
      - opened
      - reopened
      - edited

jobs:
  check-addon:
    name: Check add-on
    runs-on: windows-latest
    steps:
    - name: Get data
      id: get-data
      uses: actions/github-script@v5
      with:
        script: |
          const body = context.payload.issue.body   
          const downloadUrl = body.split("### Download URL")[1].split("###")[0].trim()
          core.setOutput('downloadUrl', downloadUrl)
          const sourceUrl = body.split("### Source URL")[1].split("###")[0].trim()
          core.setOutput('sourceUrl', sourceUrl)
          const channel = body.split("### Channel")[1].split("###")[0].trim()
          core.setOutput('channel', channel)
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Checkout validate
      uses: actions/checkout@v2
      with:
        repo: nvdaes/addon-store-validation
        path: validate
    - name: Checkout datastore
      uses: actions/checkout@v2
      with:
        repo: nvdaes/datastore
        path: datastore
    - name: Download add-on
      run: curl --location --output validate/addon.nvda-addon ${{ steps.get-data.downloadUrl }}
    - name: Create comment
      uses: actions/github-script@v5
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'add-on downloaded'
          })
          