name: Check submitted NVDA add-on

on:
  pull_request:
    branches:
      - master
      - removeTools
    paths:
      - addons/**

jobs:

  checkMetadata:
  
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Determine files changed
      uses: actions/github-script@v6
      id: getMetadata
      with:
        script: |
          const restPrefix = "GET /repos/"
          const owner = context.repo.owner
          const repo = context.repo.repo
          const number = context.issue.number
          const restSubfix = "/files"
          const url = restPrefix + owner + "/" + repo + "/pulls/" + number + restSubfix
          const result = await github.request(url)
          const changedFiles = result.data
          var addonFileName
          for (fileData of changedFiles) {
            const filename = fileData.filename
            if (filename.startsWith("addons")) {
              if (Boolean(addonFileName)){
                throw "Please submit addon releases individually. One file at a time."
              }
              if (fileData.status != "added") {
                throw "Modifications to submitted add-ons will not be auto-approved"
              }
              addonFileName = filename
            }
            else {
              throw "Non-addon-submission files updated"
            }
          }
          return addonFileName
    - name: Checkout validate repo
      uses: actions/checkout@v3
      with:
        repository: nvaccess/addon-datastore-validation
        path: addon-datastore-validation
        submodules: true
    - name: Install addon-datastore-validation dependencies
      run: |
        python -m pip install --upgrade wheel
        pip install -r addon-datastore-validation/requirements.txt
    - name: Validate metadata
      run: addon-datastore-validation/runvalidate ${{steps.getMetadata.outputs.result}}
    - name: Checkout transformation repo
      uses: actions/checkout@v3
      with:
        repository: nvaccess/addon-datastore-transform
        path: transform
    - name: Check version
      run: |
        import json
        versionsPath = os.path.join("${ github.workspace}}", "transform", "nvdaAPIVersions.json")
        versions = json.load(versionsPath)
        maxVersion = versions[-1]
        maxApiVer = maxVersion["apiVer"]
        maxVerMajor = maxApiVer["major"]
        maxVerMinor = maxApiVer["minor"]
        maxVerPatch = maxApiVer["patch"]
        addon = json.load()"$ {{ steps.getMetadata.outputs.result}}")
        lastTestedVersion = add-on["lastTestedVersion"]
        if lastTestedVersion["major"] > maxVerMajor:
          raise ValueError(f"Invalid last tested version: major > {maxVerMajor}")
        if lastTestedVersionMajor == maxVerMajor:
          if lastTestedVersionMinor > maxVerMinor:
            raise ValueError(f"Invalid version minor: minor > {maxVerMinor}")
           
      shell: python
