# https://github.com/nvaccess/addon-datastore-transform/

name: Create GitHub Discussion

on:
  workflow_call:
  workflow_dispatch:


jobs:
  createGitHubDiscussion:
    runs-on: windows-latest
    permissions:
      discussions: write

    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const mutation = `mutation {
            createDiscussion(input: {repositoryId: "MDEwOlJlcG9zaXRvcnkyMzI4NDU3MDI=", categoryId: "DIC_kwDODeDxhs4CZ6Q7", body: "The body", title: "The title"}) {
            discussion {
              id 
             }
            }
          }`;
          github.graphql(mutation)
