# https://github.com/nvaccess/addon-datastore-transform/

name: Create GitHub Discussion

on:
  workflow_call:
  workflow_dispatch:


jobs:
  createGitHubDiscussion:
    runs-on: windows-latest
    permissions:
      discussions: write


    steps:
      - uses: actions/checkout@v3
      - name: Create a new GitHub Discussion
        id: create-discussion
        uses: abirismyname/create-discussion@v1.1.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          title: Feelings
          body: |
            Let's talk!
          repository-id: '232845702'
          category-id: 'DIC_kwDODeDxhs4CZ6Q7'
