name: Test
on:
  workflow_call:
  workflow_dispatch:



jobs:
  get-cat-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                id
                name
                discussionCategories(first: 10) {
                  nodes {
                    id
                    name
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            console.log(result.data)
