# https://qiita.com/shooter/items/d59fbb43d0f118c95092

name: Test
on:
  workflow_call:
  workflow_dispatch:



jobs:
  getdiscus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner:$owner, name:$name){
                discussions() {
                  nodes {
                    id
                    title
                    category
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo
            }
            const result = await github.graphql(query, variables)
            console.log(JSON.stringify(result))