# https://qiita.com/shooter/items/d59fbb43d0f118c95092

name: Get discussions
on:
  workflow_call:
  workflow_dispatch:

jobs:
  get-discus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!, categoryId: ID!) {
              repository(owner:$owner, name:$name){
                discussions(first: 10, categoryId: $categoryId) {
                  nodes {
                    id
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              categoryId: DIC_kwDODeDxhs4CZ6Q6
            }
            const result = await github.graphql(query, variables)
            console.log(JSON.stringify(result))